# Generated by Django 6.1 on 2026-09-23 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_alter_product_additional_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug (URL)')),
                ('emoji', models.CharField(blank=True, default='', help_text='Se muestra si no hay imagen', max_length=8, verbose_name='Emoji')),
                ('image', models.ImageField(blank=True, help_text='Foto que aparece en la tarjeta del modal', null=True, upload_to='categories/', verbose_name='Imagen de fondo')),
                ('color', models.CharField(default='#e94560', help_text='Color en hex (ej: #e94560) si no hay imagen', max_length=7, verbose_name='Color de fondo')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Menor numero aparece primero', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Categoria'),
        ),
    ]
