# Generated by Django 6.1 on 2026-09-13 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_product_options_alter_product_additional_info_and_more'),
        ('stores', '0006_move_userprofile_to_accounts_app'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_payment', 'Esperando pago'), ('payment_submitted', 'Pago reportado'), ('confirmed', 'Pago confirmado'), ('shipped', 'Enviado'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending_payment', max_length=20, verbose_name='Estado')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('payment_bank', models.CharField(blank=True, max_length=100, verbose_name='Banco emisor')),
                ('payment_reference', models.CharField(blank=True, max_length=50, verbose_name='Referencia')),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='orders/proofs/', verbose_name='Comprobante')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Fecha del pago')),
                ('notes', models.TextField(blank=True, verbose_name='Notas del cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado del item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Producto')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='stores.store', verbose_name='Comercio')),
            ],
            options={
                'verbose_name': 'Item del pedido',
                'verbose_name_plural': 'Items del pedido',
            },
        ),
    ]
