# Generated by Django 6.1 on 2026-09-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reservation_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reserva vence el'),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_released',
            field=models.BooleanField(default=False, verbose_name='Stock liberado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Esperando pago'), ('payment_submitted', 'Pago reportado'), ('confirmed', 'Pago confirmado'), ('shipped', 'Enviado'), ('completed', 'Completado'), ('cancelled', 'Cancelado'), ('expired', 'Reserva expirada')], default='pending_payment', max_length=20, verbose_name='Estado'),
        ),
    ]
