# Generated by Django 6.1 on 2026-09-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_reservation_expires_at_order_stock_released_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Bs por USD')),
                ('fuente', models.CharField(choices=[('AUTO', 'Automatica (BCV)'), ('MANUAL', 'Manual')], default='AUTO', max_length=10, verbose_name='Fuente')),
                ('is_active', models.BooleanField(default=False, help_text='Si esta activa, esta tasa se usara hasta que crees otra o la desactives.', verbose_name='Usar esta tasa')),
                ('notas', models.CharField(blank=True, max_length=200, verbose_name='Notas')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tasa de cambio',
                'verbose_name_plural': 'Tasas de cambio',
                'ordering': ['-fecha', '-actualizado_en'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Tasa BCV al momento del pedido'),
        ),
    ]
