# Generated by Django 6.1 on 2026-09-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_exchangerate_order_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Solo aplica cuando el método es delivery.', verbose_name='Dirección de entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de envío'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('pickup', 'Retiro en tienda'), ('delivery', 'Delivery a domicilio')], default='pickup', max_length=10, verbose_name='Método de entrega'),
        ),
    ]
