# Generated by Django 6.1 on 2026-09-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_reference_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Esperando pago'), ('payment_submitted', 'Por verificar pago'), ('confirmed', 'Por entregar'), ('shipped', 'Enviado'), ('completed', 'Completado'), ('cancelled', 'Cancelado'), ('expired', 'Reserva expirada')], default='pending_payment', max_length=20, verbose_name='Estado'),
        ),
    ]
