# Generated by Django 6.1 on 2026-09-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('transfer', 'Transferencia bancaria'), ('mobile', 'Pago movil')], default='', max_length=20, verbose_name='Metodo de pago'),
        ),
    ]
