# Generated by Django 6.1 on 2026-09-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_add_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('transfer', 'Transferencia bancaria'), ('mobile', 'Pago movil'), ('spei', 'Transferencia SPEI'), ('mercadopago', 'Mercado Pago'), ('paypal', 'PayPal')], default='', max_length=20, verbose_name='Metodo de pago'),
        ),
    ]
