# Generated by Django 6.1.1 on 2026-10-03 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(choices=[('no_received', 'No recibí el producto'), ('wrong_product', 'Recibí un producto distinto'), ('paid_more', 'Pagué de más por error'), ('paid_less', 'Pagué de menos / referencia mal anotada'), ('not_confirmed', 'El comercio no confirmó mi pago'), ('other', 'Otro problema')], max_length=20, verbose_name='Tipo de problema')),
                ('description', models.TextField(help_text='Explica qué pasó con el pedido.', verbose_name='Descripción del problema')),
                ('evidence', models.ImageField(blank=True, help_text='Comprobante, captura de pantalla, foto del producto, etc.', null=True, upload_to='claims/evidence/', verbose_name='Evidencia (imagen)')),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('in_review', 'En revisión por el comercio'), ('resolved', 'Resuelto por el comercio'), ('closed', 'Cerrado'), ('escalated', 'Escalado al administrador'), ('rejected', 'Rechazado por el administrador')], default='open', max_length=20, verbose_name='Estado')),
                ('resolution', models.TextField(blank=True, help_text='Cómo el comercio resolvió el reclamo.', verbose_name='Resolución')),
                ('resolution_evidence', models.ImageField(blank=True, null=True, upload_to='claims/resolutions/', verbose_name='Evidencia de resolución (imagen)')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelto el')),
                ('escalated_at', models.DateTimeField(blank=True, null=True, verbose_name='Escalado el')),
                ('escalated_reason', models.TextField(blank=True, verbose_name='Motivo del escalado')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Cerrado el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_closed', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims_opened', to=settings.AUTH_USER_MODEL, verbose_name='Abierto por')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to='orders.order', verbose_name='Pedido')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_resolved', to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por')),
            ],
            options={
                'verbose_name': 'Reclamo',
                'verbose_name_plural': 'Reclamos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderClaimMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='claims/attachments/', verbose_name='Adjunto (imagen)')),
                ('is_system', models.BooleanField(default=False, help_text='Mensajes automáticos (ej: "reclamo abierto", "escalado a admin").', verbose_name='Mensaje del sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orders.orderclaim', verbose_name='Reclamo')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_messages', to=settings.AUTH_USER_MODEL, verbose_name='Remitente')),
            ],
            options={
                'verbose_name': 'Mensaje de reclamo',
                'verbose_name_plural': 'Mensajes de reclamo',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='orderclaim',
            index=models.Index(fields=['status', '-created_at'], name='orders_orde_status_b23652_idx'),
        ),
        migrations.AddIndex(
            model_name='orderclaim',
            index=models.Index(fields=['opened_by', '-created_at'], name='orders_orde_opened__acb06a_idx'),
        ),
        migrations.AddIndex(
            model_name='orderclaimmessage',
            index=models.Index(fields=['claim', 'created_at'], name='orders_orde_claim_i_cfd468_idx'),
        ),
    ]
