# Generated by Django 6.1 on 2026-09-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email verificado'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verificado el'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último envío de verificación'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_attempts_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de reenvíos'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_attempts_today',
            field=models.PositiveIntegerField(default=0, verbose_name='Reenvíos hoy'),
        ),
    ]
