# Generated by Django 6.1 on 2026-09-03 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.IntegerField(verbose_name='Cantidad (+/-)')),
                ('movement_type', models.CharField(choices=[('INIT', 'Carga inicial'), ('REST', 'Reposición'), ('SALE', 'Venta'), ('ADJ', 'Ajuste manual')], max_length=4, verbose_name='Tipo de movimiento')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Responsable')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('order_reference', models.CharField(blank=True, max_length=50, null=True, verbose_name='Referencia de pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.product', verbose_name='Producto')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Comercio')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-created_at'],
            },
        ),
    ]
