# Generated by Django 6.1 on 2026-09-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('INIT', 'Carga inicial'), ('REST', 'Reposición'), ('SALE', 'Venta'), ('RETURN', 'Devolución'), ('ADJ', 'Ajuste manual')], max_length=8, verbose_name='Tipo de movimiento'),
        ),
    ]
