# Generated by Django 6.1 on 2026-09-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_store_options_remove_store_user_auditlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación'), ('stock_adjust', 'Ajuste de stock'), ('permission_change', 'Cambio de permisos'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión')], max_length=20),
        ),
        migrations.AlterField(
            model_name='storeuserpermission',
            name='role',
            field=models.CharField(choices=[('owner', 'Propietario'), ('manager', 'Gestor/Moderador'), ('viewer', 'Visualizador')], default='manager', max_length=20),
        ),
    ]
