# Generated by Django 6.1 on 2026-09-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_move_userprofile_to_accounts_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto en dólares que se cobrará por el envío.', max_digits=10, verbose_name='Tarifa de delivery'),
        ),
        migrations.AddField(
            model_name='store',
            name='offers_delivery',
            field=models.BooleanField(default=False, help_text='Activa para permitir a los clientes pedir envío a domicilio.', verbose_name='¿Ofrece delivery?'),
        ),
    ]
