# Generated by Django 6.1 on 2026-09-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_store_delivery_fee_store_offers_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='account_holder',
            field=models.CharField(blank=True, max_length=150, verbose_name='Titular de la cuenta'),
        ),
        migrations.AddField(
            model_name='store',
            name='account_number',
            field=models.CharField(blank=True, help_text='Ej: 0102-1234-56-78901234', max_length=40, verbose_name='Número de cuenta'),
        ),
        migrations.AddField(
            model_name='store',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Ej: Banco de Venezuela, Banesco, Mercantil...', max_length=100, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='store',
            name='document',
            field=models.CharField(blank=True, help_text='Ej: V-12345678 o J-12345678-9', max_length=20, verbose_name='Cédula o RIF'),
        ),
        migrations.AddField(
            model_name='store',
            name='payment_email',
            field=models.EmailField(blank=True, help_text='A dónde te llegan las notificaciones de transferencias (opcional)', max_length=254, verbose_name='Email para notificar pagos'),
        ),
        migrations.AddField(
            model_name='store',
            name='payment_notes',
            field=models.TextField(blank=True, help_text='Información extra para el cliente (opcional)', verbose_name='Notas adicionales'),
        ),
        migrations.AddField(
            model_name='store',
            name='payment_phone',
            field=models.CharField(blank=True, help_text='Ej: 0414-1234567 (opcional, si acepta pago móvil)', max_length=20, verbose_name='Teléfono para pago móvil'),
        ),
    ]
