# Generated by Django 6.1 on 2026-09-20 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_store_account_holder_store_account_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePaymentChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_bank_name', models.CharField(blank=True, max_length=100, verbose_name='Banco (nuevo)')),
                ('new_account_number', models.CharField(blank=True, max_length=40, verbose_name='Cuenta (nueva)')),
                ('new_account_holder', models.CharField(blank=True, max_length=150, verbose_name='Titular (nuevo)')),
                ('new_document', models.CharField(blank=True, max_length=20, verbose_name='Cédula/RIF (nuevo)')),
                ('new_payment_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono (nuevo)')),
                ('old_bank_name', models.CharField(blank=True, max_length=100)),
                ('old_account_number', models.CharField(blank=True, max_length=40)),
                ('old_account_holder', models.CharField(blank=True, max_length=150)),
                ('old_document', models.CharField(blank=True, max_length=20)),
                ('old_payment_phone', models.CharField(blank=True, max_length=20)),
                ('reason', models.TextField(blank=True, verbose_name='Motivo del cambio')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de aprobación'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=20, verbose_name='Estado')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo del rechazo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_change_requests', to='stores.store', verbose_name='Comercio')),
            ],
            options={
                'verbose_name': 'Solicitud de cambio de datos bancarios',
                'verbose_name_plural': 'Solicitudes de cambio de datos bancarios',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'status'], name='stores_stor_store_i_69e1ee_idx'), models.Index(fields=['status', '-created_at'], name='stores_stor_status_49f44c_idx')],
            },
        ),
    ]
