# Generated by Django 6.1 on 2026-09-21 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_storepaymentchangerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Cerrado este día')),
                ('pickup_open', models.TimeField(blank=True, null=True, verbose_name='Retiro: abre')),
                ('pickup_close', models.TimeField(blank=True, null=True, verbose_name='Retiro: cierra')),
                ('delivery_open', models.TimeField(blank=True, null=True, verbose_name='Delivery: abre')),
                ('delivery_close', models.TimeField(blank=True, null=True, verbose_name='Delivery: cierra')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='stores.store', verbose_name='Comercio')),
            ],
            options={
                'verbose_name': 'Horario del comercio',
                'verbose_name_plural': 'Horarios del comercio',
                'ordering': ['day_of_week'],
                'unique_together': {('store', 'day_of_week')},
            },
        ),
    ]
