# Generated by Django 6.1 on 2026-09-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_storeschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='has_24_7_schedule',
            field=models.BooleanField(default=False, help_text='Si está activo, el comercio se considera siempre abierto (ignora los horarios por día).', verbose_name='¿Atiende 24/7?'),
        ),
    ]
