# Generated by Django 6.1 on 2026-09-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_store_has_24_7_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='accepts_mobile_payment',
            field=models.BooleanField(default=False, help_text='El cliente paga con pago movil al telefono del comercio.', verbose_name='¿Acepta pago movil?'),
        ),
        migrations.AddField(
            model_name='store',
            name='accepts_transfer',
            field=models.BooleanField(default=True, help_text='El cliente paga por transferencia a la cuenta del comercio.', verbose_name='¿Acepta transferencia bancaria?'),
        ),
    ]
