# Generated by Django 6.1 on 2026-09-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_add_payment_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='mobile_payment_bank',
            field=models.CharField(blank=True, help_text='Banco donde recibes el pago movil (puede ser distinto al de transferencia)', max_length=100, verbose_name='Banco receptor de pago movil'),
        ),
        migrations.AddField(
            model_name='storepaymentchangerequest',
            name='new_mobile_payment_bank',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banco pago movil (nuevo)'),
        ),
        migrations.AddField(
            model_name='storepaymentchangerequest',
            name='old_mobile_payment_bank',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
