# Generated by Django 6.1 on 2026-09-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_add_mobile_payment_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='mobile_document',
            field=models.CharField(blank=True, help_text='Cedula o RIF del titular de pago movil (puede ser distinto al de transferencia)', max_length=20, verbose_name='Cedula/RIF para pago movil'),
        ),
        migrations.AddField(
            model_name='storepaymentchangerequest',
            name='old_mobile_document',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
