# Generated by Django 6.1 on 2026-09-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_add_mobile_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepaymentchangerequest',
            name='new_mobile_document',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cedula/RIF pagomovil (nuevo)'),
        ),
    ]
