# Generated by Django 6.1 on 2026-09-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_add_new_mobile_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='mx_accepts_mercadopago',
            field=models.BooleanField(default=False, help_text='Pago via billetera digital Mercado Pago.', verbose_name='[MX] Acepta Mercado Pago'),
        ),
        migrations.AddField(
            model_name='store',
            name='mx_accepts_paypal',
            field=models.BooleanField(default=False, help_text='Pago internacional via PayPal.', verbose_name='[MX] Acepta PayPal'),
        ),
        migrations.AddField(
            model_name='store',
            name='mx_accepts_spei',
            field=models.BooleanField(default=False, help_text='Transferencia interbancaria via CLABE (18 digitos).', verbose_name='[MX] Acepta SPEI'),
        ),
        migrations.AddField(
            model_name='store',
            name='mx_mercadopago_alias',
            field=models.CharField(blank=True, help_text='Alias, CVU o link de cobro de Mercado Pago.', max_length=100, null=True, verbose_name='[MX] Alias / CLABE de Mercado Pago'),
        ),
        migrations.AddField(
            model_name='store',
            name='mx_payment_notes',
            field=models.TextField(blank=True, help_text='Informacion extra para el cliente mexicano (opcional).', verbose_name='[MX] Notas adicionales de pago'),
        ),
        migrations.AddField(
            model_name='store',
            name='mx_paypal_email',
            field=models.EmailField(blank=True, help_text='Correo asociado a la cuenta de PayPal del comercio.', max_length=254, null=True, verbose_name='[MX] Email de PayPal'),
        ),
        migrations.AddField(
            model_name='store',
            name='mx_spei_bank',
            field=models.CharField(blank=True, help_text='Ej: BBVA, Santander, Banorte, HSBC...', max_length=50, null=True, verbose_name='[MX] Banco de la CLABE'),
        ),
        migrations.AddField(
            model_name='store',
            name='mx_spei_clabe',
            field=models.CharField(blank=True, help_text='18 digitos de la CLABE del comercio.', max_length=18, null=True, verbose_name='[MX] CLABE interbancaria'),
        ),
        migrations.AddField(
            model_name='store',
            name='mx_spei_holder',
            field=models.CharField(blank=True, help_text='Nombre completo del titular de la cuenta SPEI.', max_length=150, null=True, verbose_name='[MX] Titular de la CLABE'),
        ),
        migrations.AddField(
            model_name='store',
            name='payment_region',
            field=models.CharField(choices=[('VE', 'Venezuela'), ('MX', 'Mexico')], default='VE', help_text='Determina que metodos de pago se muestran al comercio y al cliente.', max_length=2, verbose_name='Region de pagos'),
        ),
    ]
