# Generated by Django 6.1 on 2026-09-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_store_mx_accepts_mercadopago_store_mx_accepts_paypal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepaymentchangerequest',
            name='new_mx_accepts_mercadopago',
            field=models.BooleanField(default=False, verbose_name='[MX] Acepta Mercado Pago (nuevo)'),
        ),
        migrations.AddField(
            model_name='storepaymentchangerequest',
            name='new_mx_accepts_paypal',
            field=models.BooleanField(default=False, verbose_name='[MX] Acepta PayPal (nuevo)'),
        ),
        migrations.AddField(
            model_name='storepaymentchangerequest',
            name='new_mx_accepts_spei',
            field=models.BooleanField(default=False, verbose_name='[MX] Acepta SPEI (nuevo)'),
        ),
        migrations.AddField(
            model_name='storepaymentchangerequest',
            name='new_mx_mercadopago_alias',
            field=models.CharField(blank=True, max_length=100, verbose_name='[MX] Alias Mercado Pago (nuevo)'),
        ),
        migrations.AddField(
            model_name='storepaymentchangerequest',
            name='new_mx_payment_notes',
            field=models.TextField(blank=True, verbose_name='[MX] Notas de pago (nuevas)'),
        ),
        migrations.AddField(
            model_name='storepaymentchangerequest',
            name='new_mx_paypal_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='[MX] Email PayPal (nuevo)'),
        ),
        migrations.AddField(
            model_name='storepaymentchangerequest',
            name='new_mx_spei_bank',
            field=models.CharField(blank=True, max_length=50, verbose_name='[MX] Banco SPEI (nuevo)'),
        ),
        migrations.AddField(
            model_name='storepaymentchangerequest',
            name='new_mx_spei_clabe',
            field=models.CharField(blank=True, max_length=18, verbose_name='[MX] CLABE (nueva)'),
        ),
        migrations.AddField(
            model_name='storepaymentchangerequest',
            name='new_mx_spei_holder',
            field=models.CharField(blank=True, max_length=150, verbose_name='[MX] Titular CLABE (nuevo)'),
        ),
        migrations.AddField(
            model_name='storepaymentchangerequest',
            name='old_mx_accepts_mercadopago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storepaymentchangerequest',
            name='old_mx_accepts_paypal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storepaymentchangerequest',
            name='old_mx_accepts_spei',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storepaymentchangerequest',
            name='old_mx_mercadopago_alias',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='storepaymentchangerequest',
            name='old_mx_payment_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='storepaymentchangerequest',
            name='old_mx_paypal_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='storepaymentchangerequest',
            name='old_mx_spei_bank',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='storepaymentchangerequest',
            name='old_mx_spei_clabe',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name='storepaymentchangerequest',
            name='old_mx_spei_holder',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
